version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=task_dev
      - POSTGRES_USER=task_dev
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  api:
    restart: 'always'
    command: npm start
    build: .
    environment:
      - DB_HOSTNAME=db
      - TYPEOR_SYNC=true
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
