version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks_http
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      - tasks-backend
  http:
    command: npm run start:dev
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - tasks-backend
    depends_on:
      - db

networks:
  tasks-backend:
    name: tasks-backend
